"""Image-to-bucket assignment by nearest aspect ratio.

Assigns each image to the closest valid training bucket, following the
NovelAI/kohya algorithm: argmin of absolute aspect ratio difference.
Buckets are generated by generate_buckets() from config/model_profiles.py.
"""

from __future__ import annotations


def assign_to_bucket(
    width: int,
    height: int,
    buckets: list[tuple[int, int]],
    max_aspect_ratio: float = 2.0,
) -> tuple[int, int] | None:
    """Find the nearest bucket for an image by aspect ratio.

    Args:
        width: Image width in pixels.
        height: Image height in pixels.
        buckets: Valid bucket dimensions from generate_buckets().
        max_aspect_ratio: Maximum allowed aspect ratio (long/short).
            Images exceeding this return None.

    Returns:
        (bucket_width, bucket_height) tuple, or None if the image's
        aspect ratio exceeds max_aspect_ratio or bucket list is empty.
    """
    if not buckets or height == 0:
        return None

    # Check if image has extreme aspect ratio
    image_max_ar = max(width, height) / min(width, height)
    if image_max_ar > max_aspect_ratio:
        return None

    image_ar = width / height
    return min(buckets, key=lambda b: abs(b[0] / b[1] - image_ar))


def needs_upscale(
    image_width: int,
    image_height: int,
    bucket_width: int,
    bucket_height: int,
) -> bool:
    """Check if image needs upscaling to fill assigned bucket.

    Returns True if either image dimension is smaller than the
    corresponding bucket dimension.

    Args:
        image_width: Source image width.
        image_height: Source image height.
        bucket_width: Assigned bucket width.
        bucket_height: Assigned bucket height.

    Returns:
        True if upscaling would be needed.
    """
    return image_width < bucket_width or image_height < bucket_height
